#!/bin/bash
# ulh - Your own files. Updates never touch them (both folders are git-ignored).
#
#   config/repo.yaml     your repositories (created from repo.yaml.example)
#   config/answer.yaml   preset answers and autoscript (optional)
#   data/keys/           SSH keys for private repositories
#   data/repos/<path>/   your repositories: own config.yaml + scripts/
#   data/lib/            generated: scripts in your repositories load ulh's
#                        helpers with "$(dirname "$0")/../../../lib/bootstrap.sh"

# ============================================================================
# Take over the old custom/ folder
# ============================================================================
# Before 2026-09-22 all of this lived in custom/ at the top of the clone.
# Runs on every start and only moves what is still there: nothing is
# overwritten, nothing of yours is deleted.
# Compatibility: can go once no installation from before 2026-09-22 is
# expected any more - then also delete custom/repo.yaml and
# custom/demo-scripts/scripts/file-backup.sh from the repository.

userdata_migrate() {
    local old="${ULH_ROOT}/custom"
    [[ -d "$old" ]] || return 0

    local cfg="${ulh_DIR}/config" data="${ulh_DIR}/data"
    local moved=0 f name

    # Still in git, so that `git pull` of old installations never stops at a
    # changed copy. Unchanged: ours, remove it. Changed: yours, move it.
    _userdata_take "custom/repo.yaml" "$cfg/repo.yaml" && moved=1
    _userdata_take "custom/demo-scripts/scripts/file-backup.sh" \
        "$data/repos/demo-scripts/scripts/file-backup.sh" && moved=1
    rmdir "$old/demo-scripts/scripts" "$old/demo-scripts" 2>/dev/null

    # Never in git: preset answers, SSH keys, your repositories
    _userdata_move "$old/answer.yaml" "$cfg/answer.yaml" && moved=1

    if [[ -d "$old/keys" ]]; then
        for f in "$old/keys"/* "$old/keys"/.[!.]*; do
            [[ -e "$f" ]] || continue
            name="${f##*/}"
            [[ "$name" == ".gitignore" ]] && continue
            _userdata_move "$f" "$data/keys/$name" && moved=1
        done
        rmdir "$old/keys" 2>/dev/null
    fi

    for f in "$old"/*/; do
        [[ -d "$f" ]] || continue
        name="$(basename "$f")"
        [[ "$name" == "keys" ]] && continue
        _userdata_move "${f%/}" "$data/repos/$name" && moved=1
    done

    rmdir "$old" 2>/dev/null
    if (( moved )); then
        msg_info "Your files moved from custom/ to apps/cli/config/ and apps/cli/data/"
    fi
    return 0
}

# A file the old version shipped in git: $1 path in the clone, $2 new place.
# Returns 0 only if a changed copy was moved.
_userdata_take() {
    local rel="$1" dest="$2"
    [[ -f "${ULH_ROOT}/${rel}" ]] || return 1

    if git -C "$ULH_ROOT" ls-files --error-unmatch -- "$rel" &>/dev/null &&
       git -C "$ULH_ROOT" -c core.fileMode=false diff --quiet HEAD -- "$rel" 2>/dev/null; then
        rm -f "${ULH_ROOT}/${rel}"
        return 1
    fi
    _userdata_move "${ULH_ROOT}/${rel}" "$dest"
}

# Move $1 to $2 unless $2 already exists
_userdata_move() {
    local src="$1" dest="$2"
    [[ -e "$src" || -L "$src" ]] || return 1
    if [[ -e "$dest" || -L "$dest" ]]; then
        msg_warn "Not moved, already there: ${dest#"$ULH_ROOT"/} (old copy: ${src#"$ULH_ROOT"/})"
        return 1
    fi
    if mkdir -p "$(dirname "$dest")" && mv "$src" "$dest"; then
        return 0
    fi
    msg_warn "Could not move ${src#"$ULH_ROOT"/}"
    return 1
}

# ============================================================================
# Create what is missing
# ============================================================================

userdata_init() {
    local cfg="${ulh_DIR}/config" data="${ulh_DIR}/data" tpl="${ulh_DIR}/templates"
    local f

    mkdir -p "$cfg" "$data/repos" "$data/keys" "$data/lib" 2>/dev/null
    chmod 700 "$data/keys" 2>/dev/null

    _userdata_copy "$cfg/repo.yaml.example" "$cfg/repo.yaml"

    # The demo repository (switched off in repo.yaml)
    local demo="$data/repos/demo-scripts"
    if [[ ! -f "$demo/config.yaml" ]]; then
        mkdir -p "$demo/scripts" 2>/dev/null
        _userdata_copy "$tpl/demo-config.yaml" "$demo/config.yaml"
        _userdata_copy "$tpl/demo-readme.md" "$demo/README.md"
        for f in hello system-info file-backup; do
            _userdata_copy "$tpl/demo-${f}.sh" "$demo/scripts/${f}.sh"
        done
    fi

    # Scripts in your repositories load ulh's helpers from ../../../lib/
    local want
    for f in bootstrap colors; do
        want="# Generated by ulh - scripts in data/repos/<repo>/scripts/ load this as ../../../lib/${f}.sh
source \"\${BASH_SOURCE%/*}/../../classes/${f}.sh\""
        if [[ "$(cat "$data/lib/${f}.sh" 2>/dev/null)" != "$want" ]]; then
            printf '%s\n' "$want" > "$data/lib/${f}.sh" 2>/dev/null
        fi
    done
    return 0
}

# Copy $1 to $2 unless $2 already exists
_userdata_copy() {
    [[ -e "$2" ]] || cp "$1" "$2" 2>/dev/null
    return 0
}
