#!/bin/bash

# openssh - Secure Shell remote access
# Install, update, uninstall, and configure OpenSSH on all Linux distributions

set -e

# Parse action from first parameter
ACTION="${1%%,*}"

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

# Log informational messages with green checkmark
log_info() {
    printf "${GREEN}✓${NC} %s\n" "$1"
}

# Log error messages with red X and exit
log_error() {
    printf "${RED}✗${NC} %s\n" "$1"
    exit 1
}

# Detect operating system and set appropriate package manager commands
detect_os() {
    source /etc/os-release || log_error "Cannot detect OS"
    
    case "${ID,,}" in
        ubuntu|debian|raspbian|linuxmint|pop)
            PKG_UPDATE="apt-get update"
            PKG_INSTALL="apt-get install -y"
            PKG_UNINSTALL="apt-get remove -y"
            ;;
        fedora|rhel|centos|rocky|alma)
            PKG_UPDATE="dnf check-update || true"
            PKG_INSTALL="dnf install -y"
            PKG_UNINSTALL="dnf remove -y"
            ;;
        arch|manjaro|endeavouros)
            PKG_UPDATE="pacman -Sy"
            PKG_INSTALL="pacman -S --noconfirm"
            PKG_UNINSTALL="pacman -R --noconfirm"
            ;;
        opensuse*|sles)
            PKG_UPDATE="zypper refresh"
            PKG_INSTALL="zypper install -y"
            PKG_UNINSTALL="zypper remove -y"
            ;;
        alpine)
            PKG_UPDATE="apk update"
            PKG_INSTALL="apk add"
            PKG_UNINSTALL="apk del"
            ;;
        *)
            log_error "Unsupported distribution"
            ;;
    esac
}

# Install OpenSSH server
install_openssh() {
    log_info "Installing openssh-server..."
    detect_os
    
    sudo $PKG_UPDATE || true
    sudo $PKG_INSTALL openssh-server || log_error "Failed"
    
    # Enable SSH service (handle both 'ssh' and 'sshd' service names)
    sudo systemctl enable ssh || sudo systemctl enable sshd
    
    log_info "openssh-server installed and enabled!"
}

# Update OpenSSH server
update_openssh() {
    log_info "Updating openssh-server..."
    detect_os
    
    sudo $PKG_UPDATE || true
    sudo $PKG_INSTALL openssh-server || log_error "Failed"
    
    log_info "openssh-server updated!"
}

# Uninstall OpenSSH server
uninstall_openssh() {
    log_info "Uninstalling openssh-server..."
    detect_os
    
    # Disable SSH service (handle both 'ssh' and 'sshd' service names)
    sudo systemctl disable sshd || sudo systemctl disable ssh
    sudo $PKG_UNINSTALL openssh-server || log_error "Failed"
    
    log_info "openssh-server uninstalled!"
}

# Configure OpenSSH server interactively
configure_openssh() {
    log_info "Configuring OpenSSH server..."
    
    # Ensure sshd_config.d directory exists
    sudo mkdir -p /etc/ssh/sshd_config.d
    
    # Prompt for all SSH configuration settings
    read -p "SSH Port (default: 22): " SSH_PORT
    SSH_PORT="${SSH_PORT:-22}"
    
    read -p "Password Authentication (yes/no, default: yes): " PASS_AUTH
    PASS_AUTH="${PASS_AUTH:-yes}"
    
    read -p "Public Key Authentication (yes/no, default: yes): " PUBKEY_AUTH
    PUBKEY_AUTH="${PUBKEY_AUTH:-yes}"
    
    read -p "Permit Root Login (yes/no/prohibit-password, default: prohibit-password): " PERMIT_ROOT
    PERMIT_ROOT="${PERMIT_ROOT:-prohibit-password}"
    
    read -p "X11 Forwarding (yes/no, default: no): " X11_FORWARD
    X11_FORWARD="${X11_FORWARD:-no}"
    
    read -p "Login Grace Time in seconds (default: 120): " LOGIN_GRACE
    LOGIN_GRACE="${LOGIN_GRACE:-120}"
    
    read -p "Max Auth Tries (default: 6): " MAX_AUTH
    MAX_AUTH="${MAX_AUTH:-6}"
    
    read -p "Max Sessions (default: 10): " MAX_SESSIONS
    MAX_SESSIONS="${MAX_SESSIONS:-10}"
    
    read -p "Allow Users (comma-separated, optional): " ALLOW_USERS
    
    read -p "Allow Groups (comma-separated, optional): " ALLOW_GROUPS
    
    read -p "Client Alive Interval in seconds (default: 300): " CLIENT_ALIVE
    CLIENT_ALIVE="${CLIENT_ALIVE:-300}"
    
    # Create configuration content
    CONFIG_CONTENT="# OpenSSH configuration generated by liauh
# Do not edit manually - use liauh openssh config action

Port $SSH_PORT
PasswordAuthentication $PASS_AUTH
PubkeyAuthentication $PUBKEY_AUTH
PermitRootLogin $PERMIT_ROOT
X11Forwarding $X11_FORWARD
LoginGraceTime $LOGIN_GRACE
MaxAuthTries $MAX_AUTH
MaxSessions $MAX_SESSIONS
ClientAliveInterval $CLIENT_ALIVE
"
    
    # Add optional settings if provided
    if [[ -n "$ALLOW_USERS" ]]; then
        CONFIG_CONTENT+="AllowUsers $ALLOW_USERS"$'\n'
    fi
    
    if [[ -n "$ALLOW_GROUPS" ]]; then
        CONFIG_CONTENT+="AllowGroups $ALLOW_GROUPS"$'\n'
    fi
    
    # Write configuration to liauh.conf
    echo "$CONFIG_CONTENT" | sudo tee /etc/ssh/sshd_config.d/liauh.conf > /dev/null
    
    # Validate SSH configuration
    if ! sudo sshd -t; then
        log_error "SSH configuration validation failed"
    fi
    
    log_info "Configuration written to /etc/ssh/sshd_config.d/liauh.conf"
    
    # Restart SSH service
    if ! sudo systemctl restart sshd && ! sudo systemctl restart ssh; then
        log_error "Failed to restart SSH service"
    fi
    
    log_info "OpenSSH server configured and restarted successfully!"
}

# Route to appropriate action
case "$ACTION" in
    install)
        install_openssh
        ;;
    update)
        update_openssh
        ;;
    uninstall)
        uninstall_openssh
        ;;
    config)
        configure_openssh
        ;;
    *)
        log_error "Unknown action: $ACTION"
        ;;
esac
