#!/bin/bash
# Writes docs/scripts.md from the catalog (apps/cli/assets/catalog.yaml).
# Run on Linux after changing the catalog:  bash tools/gen-scripts-doc.sh
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
catalog="${root}/apps/cli/assets/catalog.yaml"
out="${root}/docs/scripts.md"
version="$(tr -d '[:space:]' < "${root}/apps/cli/VERSION")"

case "$(uname -m)" in
    x86_64)        yq="${root}/apps/cli/vendor/yq/yq-amd64" ;;
    aarch64|arm64) yq="${root}/apps/cli/vendor/yq/yq-arm64" ;;
    armv7l)        yq="${root}/apps/cli/vendor/yq/yq-arm" ;;
    i686)          yq="${root}/apps/cli/vendor/yq/yq-386" ;;
    *) echo "Unsupported architecture: $(uname -m)" >&2; exit 1 ;;
esac

# One line per script, fields separated by | (never part of a description):
# name|category|description|actions|sudo|os_family|os_only
rows="$("$yq" -r '.scripts | to_entries | .[] | [.key, .value.category, .value.description,
    (.value.actions | map(.name) | join(", ")), (.value | has("sudo")),
    ((.value.os_family // []) | join(", ")),
    ((.value.os_only // []) | [.] | flatten | join(", "))] | join("|")' "$catalog")"

# Categories in catalog order, with their description
declare -A catdesc
mapfile -t cats < <("$yq" -r '.categories | keys | .[]' "$catalog")
while IFS='|' read -r c d; do
    catdesc["$c"]="$d"
done < <("$yq" -r '.categories | to_entries | .[] | [.key, (.value.description // "")] | join("|")' "$catalog")

anchor() { local a="${1,,}"; a="${a//[^a-z0-9 -]/}"; echo "${a// /-}"; }

{
    echo "# ulh Scripts Reference"
    echo ""
    echo "**v${version} | $(printf '%s\n' "$rows" | grep -c .) scripts | ${#cats[@]} categories**"
    echo ""
    echo "Every script is \`apps/cli/assets/scripts/<name>.sh\`; its menu entry, actions and"
    echo "prompts are in \`apps/cli/assets/catalog.yaml\`. \`sudo\` = the actions run via sudo."
    echo "\`Distros\`: \`all\` = Debian, Red Hat, Arch, SUSE and Alpine families."
    echo ""
    echo "Generated by \`bash tools/gen-scripts-doc.sh\` - do not edit by hand."
    echo ""
    echo "## Table of Contents"
    echo ""
    for c in "${cats[@]}"; do echo "- [$c](#$(anchor "$c"))"; done
    echo ""
    echo "---"
    for c in "${cats[@]}"; do
        lines="$(printf '%s\n' "$rows" | awk -F'|' -v c="$c" '$2 == c' | sort)"
        n="$(printf '%s\n' "$lines" | grep -c . || true)"
        echo ""
        echo "## $c"
        echo ""
        echo "*${catdesc[$c]}* - ${n} scripts"
        echo ""
        echo "| Script | Description | Actions | sudo | Distros |"
        echo "|--------|-------------|---------|------|---------|"
        while IFS='|' read -r name _ desc actions sudo fam only; do
            [[ -n "$name" ]] || continue
            if [[ -n "$only" ]]; then
                distros="only ${only}"
            elif [[ -z "$fam" || "$(tr -d ' ' <<< "$fam" | tr ',' '\n' | sort | paste -sd,)" == "alpine,arch,debian,redhat,suse" ]]; then
                distros="all"
            else
                distros="$fam"
            fi
            [[ "$sudo" == "true" ]] && sudo="yes" || sudo="-"
            echo "| \`${name}\` | ${desc} | ${actions} | ${sudo} | ${distros} |"
        done <<< "$lines"
    done
} > "$out"

echo "Written: ${out#"$root"/}"
